config/routes.rb
Rails.application.routes.draw do
  resources :tenancies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "cars#index"
  
  resources :cars do
    collection do
      get 'manufacturers', to: 'cars#manufacturers', as: 'manufacturers'
      get 'models',        to: 'cars#models',        as: 'models'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    validates :model, :manufacturer, :plate, :model_year, :manufacturer_year, presence: true
end

app/models/tenancy.rb
class Tenancy < ApplicationRecord
  validates :tenant_cpf, numericality: true, presence: true
  validates :checkin, :checkout, presence: true
  validates_length_of :tenant_cpf, minimum: 11, maximum: 11, allow_blank: false
  belongs_to :car

  validate :check_availability

  def check_availability
      vehicle_tenancies = Tenancy.where(car_id: self.car_id)

      if vehicle_tenancies.present?
          checkin_match_tenancies = vehicle_tenancies.where(checkin: self.checkin..self.checkout).where.not(id: self.id).exists?
          checkout_match_tenancies = vehicle_tenancies.where(checkout: self.checkin..self.checkout).where.not(id: self.id).exists?

          if checkin_match_tenancies
              self.errors.add(:checkin, "date is not unavailable to this vehicle")
          end

          if checkout_match_tenancies
              self.errors.add(:checkin, "date is not unavailable to this vehicle")
          end
      end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true
require 'net/http' #move to lib

class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    manufacturers
  end

  # GET /cars/1/edit
  def edit
    manufacturers
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        manufacturers
        
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        manufacturers
        
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def manufacturers
    url = URI.parse('http://fipeapi.appspot.com/api/1/carros/marcas.json')
    req = Net::HTTP::Get.new(url.to_s)

    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    
    if res.kind_of? Net::HTTPSuccess
      @manufacturers = JSON.parse(res.body).map { |manufacturer| { 'name' => manufacturer['fipe_name'], 'id' => manufacturer['id'] } }
      
      if @car.id?
        car_manufacturer = @manufacturers.find { |ma| ma['name'] == @car.manufacturer } 
        @selected_manufaturer = car_manufacturer['id']
      end
    else
      render_404
    end
  end

  def models
    if params[:manufacturer_id].present?
      url = URI.parse("http://fipeapi.appspot.com/api/1/carros/veiculos/#{params[:manufacturer_id]}.json")
      req = Net::HTTP::Get.new(url.to_s)
  
      res = Net::HTTP.start(url.host, url.port) {|http|
        http.request(req)
      }
      
      if res.kind_of? Net::HTTPSuccess
        @models = JSON.parse(res.body)
      else
        render_404
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:model, :manufacturer, :plate, :model_year, :manufacturer_year)
  end
end

app/controllers/tenancies_controller.rb
class TenanciesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_tenancy, only: [:show, :edit, :update, :destroy]

  # GET /tenancies
  # GET /tenancies.json
  def index
    @tenancies = Tenancy.all
  end

  # GET /tenancies/1
  # GET /tenancies/1.json
  def show
  end

  # GET /tenancies/new
  def new
    @tenancy = Tenancy.new
  end

  # GET /tenancies/1/edit
  def edit
  end

  # POST /tenancies
  # POST /tenancies.json
  def create
    @tenancy = Tenancy.new(tenancy_params)

    respond_to do |format|
      if @tenancy.save
        format.html { redirect_to @tenancy, notice: 'Tenancy was successfully created.' }
        format.json { render :show, status: :created, location: @tenancy }
      else
        format.html { render :new }
        format.json { render json: @tenancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenancies/1
  # PATCH/PUT /tenancies/1.json
  def update
    respond_to do |format|
      if @tenancy.update(tenancy_params)
        format.html { redirect_to @tenancy, notice: 'Tenancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenancy }
      else
        format.html { render :edit }
        format.json { render json: @tenancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenancies/1
  # DELETE /tenancies/1.json
  def destroy
    @tenancy.destroy
    respond_to do |format|
      format.html { redirect_to tenancies_url, notice: 'Tenancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenancy
      @tenancy = Tenancy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenancy_params
      params.require(:tenancy).permit(:checkin, :checkout, :tenant_cpf, :car_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/tenancies_helper.rb
module TenanciesHelper
end

app/views/cars/_form.html.erb
<div class="col-12">
  <%= form_for(car) do |f| %>
    <% if car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

        <ul>
        <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-6">
      <%= label_tag :manufacturer %>
      <%= select_tag 'manufacturer_options', options_for_select([nil] + @manufacturers.map { |opt| [opt['name'], opt['id']] },
      @selected_manufaturer), onchange: 'get_models()', class: "form-control" %>

      <small id="emailHelp" class="form-text text-muted">Select a manufacturer and next a model.</small>
      <%= f.hidden_field :manufacturer, class: "form-control" %>
    </div>

    <div class="form-group col-6">
        <%= f.label :model %>
        <%= f.select :model, car.present? ? [car.model, car.model] : [], class: "form-control" %>
    </div>


    <div class="form-group col-6">
        <%= f.label :plate %>
        <%= f.text_field :plate, { prompt: 'Informe uma Placa', class: "form-control" } %>
    </div>

    <div class="form-group col-6">
        <%= f.label :model_year %>
        <%= f.number_field :model_year, { prompt: 'Informe o Ano do modelo', class: "form-control" } %>
    </div>

    <div class="form-group col-6">
        <%= f.label :manufacturer_year %>
        <%= f.number_field :manufacturer_year, { prompt: 'Informe o Ano de fabricação', class: "form-control" } %>
    </div>

    <div class="actions col-6">
      <%= f.submit "Create", :class => "btn btn-primary" %>
      <%= link_to 'Back', cars_path, class: "btn btn-secondary" %>
      
      <% if action_name == 'edit' %>
        <%= link_to 'Show', @car, class: "btn btn-info" %>
      <% end %>
    </div>
  <% end %>
</div>


<script>
  function get_models(){
    $.ajax({
      url: "/models",
      type: "GET",
      dataType: "script",
      data: { manufacturer_id: $('#manufacturer_options option:selected').val() }
    })
  };

  $("#car_model").change(function(){
    let manufacturer = $('#car_model option:selected')[0].dataset.manufacturer
    $('#car_manufacturer').val(manufacturer)
  });
</script>

app/views/cars/edit.html.erb
<div class="col-12">
    <h1>Editing Car</h1>
</div>

<div class="col-12">
    <%= render 'form', car: @car %>
</div>

app/views/cars/index.html.erb
<div class="col-12 text-center">
  <%= link_to 'Rent a car here!', tenancies_path, class: 'btn btn-success', style: "margin: 20px;" %>
</div>

<div class="row">
  <div class="col-10 d-flex justify-content-center">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="col-12">
    <div class="col-12">
      <h1>Cars</h1>
    </div>

    <div class="col-12">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Model</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Plate</th>
            <th scope="col">Model year</th>
            <th scope="col">Manufacturer year</th>
            <th scope="col" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @cars.each do |car| %>
            <tr>
              <th scope="row"><%= car.id %></th>
              <td><%= car.model %></td>
              <td><%= car.manufacturer %></td>
              <td><%= car.plate %></td>
              <td><%= car.model_year %></td>
              <td><%= car.manufacturer_year %></td>
              <td><%= link_to 'Show', car %></td>
              <td><%= link_to 'Edit', edit_car_path(car) %></td>
              <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-12">
      <%= link_to 'New Car', new_car_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/cars/models.js.erb
$('#car_model').empty();

<% if @models.present? %>
  <% @models.each do |model| %>
    $('#car_model').append($('<option value="<%= model["fipe_name"] %>" data-manufacturer="<%= model["fipe_marca"] %>"><%= model["fipe_name"] %></option>'));
  <% end %>
<% end %>

app/views/cars/new.html.erb
<div class="col-12">
    <h1>New Car</h1>
</div>

<div class="col-12">
    <%= render 'form', car: @car %>
</div>

app/views/cars/show.html.erb
<div class="col-12">
  <p id="notice"><%= notice %></p>

  <div class="col-12">
    <h3 class="text-center">
      <%= @car.model %>
    </h3>
  </div>
</div>

<div class="col-12">
  <div class="text-center">
    <div class="col-12">
      <p>
        <strong>Manufacturer:</strong>
        <%= @car.manufacturer %>
      </p>
    </div>

    <div class="col-12">
      <p>
        <strong>Plate:</strong>
        <%= @car.plate %>
      </p>
    </div>

    <div class="col-12">
      <p>
        <strong>Model year:</strong>
        <%= @car.model_year %>
      </p>
    </div>

    <div class="col-12">
      <p>
        <strong>Manufacturer year:</strong>
        <%= @car.manufacturer_year %>
      </p>
    </div>
  </div>

  <div class="col-12 text-center">
    <%= link_to 'Edit', edit_car_path(@car), class: 'btn btn-primary' %>
    <%= link_to 'Back', cars_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarLocator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if user_signed_in? %>
      <p>
        Logged user: <%= current_user.name %>

        <%= link_to "Sair", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true } %>
      </p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/tenancies/_form.html.erb
<div class="col-12">
  <%= form_for(tenancy) do |f| %>
    <% if tenancy.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tenancy.errors.count, "error") %> prohibited this tenancy from being saved:</h2>

        <ul>
        <% tenancy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-6">
      <%= f.label :checkin %>
      <%= f.datetime_select :checkin %>
    </div>

    <div class="form-group col-6">
      <%= f.label :checkout %>
      <%= f.datetime_select :checkout %>
    </div>

    <div class="form-group col-6">
      <%= f.label :tenant_cpf %>
      <%= f.text_field :tenant_cpf, :maxlength => 11 %>
    </div>

    <div class="form-group col-6">
      <%= f.label :car %>
      <%= f.select :car_id, Car.all.collect { |car| [ car.model, car.id ] } %>
    </div>

    <div class="actions col-6">
      <%= f.submit "Confirm", :class => "btn btn-primary" %>
      <%= link_to 'Back', tenancies_path, class: "btn btn-secondary" %>
      
      <% if action_name == 'edit' %>
        <%= link_to 'Show', @tenancy, class: "btn btn-info" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tenancies/edit.html.erb
<div class="col-12">
    <h1>Editing Tenancy</h1>
</div>

<div class="col-12">
    <%= render 'form', tenancy: @tenancy %>
</div>

app/views/tenancies/index.html.erb
<div class="col-12 text-center">
  <% if current_user.present? %>
    <%= link_to 'Cars list', cars_path, class: 'btn btn-success', style: "margin: 20px;" %>    
  <% else %>
    <%= link_to 'Log in', new_user_session_path, class: 'btn btn-success', style: "margin: 20px;" %>
  <% end %>
</div>
 
<div class="row">
  <div class="col-10 d-flex justify-content-center">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="col-12">
    <div class="col-12">
      <h1>Tenancies</h1>
    </div>

    <div class="col-12">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Check in</th>
            <th scope="col">Check out</th>
            <th scope="col">Tenant cpf</th>
            <th scope="col">Car</th>
            <th scope="col" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @tenancies.each do |tenancy| %>
            <tr>
              <th scope="row"><%= tenancy.id %></th>
             <td><%= tenancy.checkin %></td>
            <td><%= tenancy.checkout %></td>
            <td><%= tenancy.tenant_cpf %></td>
            <td><%= tenancy.car.model %></td>
            <td><%= link_to 'Show', tenancy %></td>
            <td><%= link_to 'Edit', edit_tenancy_path(tenancy) %></td>
            <td><%= link_to 'Destroy', tenancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-12">
      <%= link_to 'New rent', new_tenancy_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/tenancies/new.html.erb
<div class="col-12">
    <h1>New Rent</h1>
</div>

<div class="col-12">
    <%= render 'form', tenancy: @tenancy %>
</div>

app/views/tenancies/show.html.erb
<div class="col-12">
  <p id="notice"><%= notice %></p>

  <div class="col-12">
    <h3 class="text-center">
      Rent ID: #<%= @tenancy.id %>
    </h3>
  </div>
</div>

<div class="col-12">
  <div class="text-center">
    <div class="col-12">
      <p>
        <strong>Checkin:</strong>
        <%= @tenancy.checkin %>
      </p>
    </div>
  </div>

  <div class="text-center">
    <div class="col-12">
      <p>
        <strong>Checkout:</strong>
        <%= @tenancy.checkout %>
      </p>
    </div>
  </div>

  <div class="text-center">
    <div class="col-12">
      <p>
        <strong>Tenant cpf:</strong>
        <%= @tenancy.tenant_cpf %>
      </p>
    </div>
  </div>

  <div class="text-center">
    <div class="col-12">
      <p>
        <strong>Car:</strong>
        <%= @tenancy.car.model %>
      </p>
    </div>
  </div>

  <div class="col-12 text-center">
    <%= link_to 'Edit', edit_tenancy_path(@tenancy), class: 'btn btn-primary' %>
    <%= link_to 'Back', tenancies_path, class: 'btn btn-secondary' %>
  </div>
</div>